### ISSUE TITLE
Conflict version 

### ISSUE THREAD

**Issue by purepure** [yixia/VitamioBundle#122]
Hi!
I am using version 4.1.1 and just upgrade to the latest version. Simply by running pull request and replace the old one. But when I run, it seem to be there is conflict between 2 versions.
When run at the first time, the application copy all needed library into the sandbox folder. When install the new one, it will not copy new libs into sandbox because it does not detect the version. 
It mean when replace the new library, it will not update at runtime -> user who has already install my app will get crash if update my app. 
Can you implement some function to fix that issue?
Thank

**Comment by rfoa** [comment]
Happens to me the same problem ...
The difference is that I am upgrading directly from version 3.0 to 4.2.2.
What should I do?

@purepure You could solve this problem?
If yes, what did you do?

@crossle You say in relation to AndroidManifest of my own project?
Yes, even if I update the android: versionCode the error continues.

Thanks to all
