### ISSUE TITLE
HLS playback broken since last update

### ISSUE THREAD

**Issue by Ltty** [yixia/VitamioBundle#130]
Since the last update I cannot playback M3U8 playlists anymore. MediaPlayer crashes with 04-21 10:40:21.477: E/Vitamio[Player](9651): Error (1, -5), Video view loads forever and has about 10 seconds delay for live streaming. The framework worked well before. Please have a look at it and fix it!

Getting errors such as invalid band type, prediction is not allowed, number of bands exceeded, channel element is not allowed. The stream is still the same as before. I did not changed it between the versions and it worked well before.

Another exception that occurs is 04-21 10:50:27.133: E/AndroidRuntime(11072): java.lang.NoSuchMethodError: no static or non-static method "Lio/vov/vitamio/MediaPlayer;._setVideoSurface(Landroid/view/Surface;)V"

**Comment by iamnitesh** [comment]
is there any solution for the above error because i am also facing the same issue.
`java.lang.NoSuchMethodError: no static or non-static method "Lio/vov/vitamio/MediaPlayer;._setVideoSurface(Landroid/view/Surface;)V"`

please reply if anyone knows solution.Thank you

**Comment by MythodeaLoL** [comment]
@iamnitesh this issue is 2 years old, not relevant.
