### ISSUE TITLE
Can Vitamio send video data to Chromecast? (RTMP + FLV, etc...)

### ISSUE THREAD

**Issue by bdovaz** [yixia/VitamioBundle#138]
Normally with Chromecast SDK you set an online url with an MP4 video files accross HTTP protocol.

But there are many pages that use RTMP with FLVs.

Is there any way that Vitamio "reads that" and sends it to Chromecast?

Thanks!

**Comment by alexandre-mbm** [comment]
Seems the Chromecast does not support RMTP.

**Comment by MythodeaLoL** [comment]
Vitamio support cast screen to chromecast @crossle ?

**Comment by crossle** [comment]
@MelissaTaylor  Dont support cast screen

**Comment by MythodeaLoL** [comment]
Maybe via ffmpeg pip/udp output its is possible, enabling upnp/dlna streaming for smart tvs.
https://github.com/cybergarage/cybergarage-upnp

I saw an app that has implemented it using the vitamio, unfortunately there are no examples of how to use this with vitamio, simple and easy to implement.
@crossle @N3uRo @alexandre-mbm

**Comment by MythodeaLoL** [comment]
after 8 years? loool 🤣 oh men 🏸 @bdovaz
