### ISSUE TITLE
Subtitles can not work

### ISSUE THREAD

**Issue by kietcao** [yixia/VitamioBundle#150]
I used last version.
 - I download VitamioBundle on 2014/06/10
 - I used version VitamioBundle-4.2.2

But I was tried to subtitles. I did step by step and can not work.
1. VideoViewSubtitle (io.vov.vitamio.demo)
1.1 I used real path : example: http://domain/subtitles.srt -> Player can not work.
mVideoView.addTimedTextSource(subtitle_path);
mVideoView.setTimedTextShown(true);
1.2 I stored real path to ExternalStorageDirectory - > Player also can not work.
String sub_path = CacheStore.getInstance().getCacheFile(subtitle_path);
if (sub_path == null) sub_path = CacheStore.getInstance().saveCacheFile(subtitle_path);
mVideoView.addTimedTextSource(sub_path);
mVideoView.setTimedTextShown(true);

2. MediaPlayerSubtitle (io.vov.vitamio.demo)
I did similar VideoViewSubtitle such as used real path and stored real path to ExternalStorageDirectory. Player also can not work.

Please let me know how I can play subtitles.
Please show my logs.
06-10 17:30:40.393: E/Vitamio[4.2.1][Player](25156): NO SUBTITLE STREAM!
06-10 17:30:40.393: E/Vitamio[4.2.1][Player](25156): NO SUBTITLE DATA FOUND -1

I was tried to make wrong subtitle_path and saw logs.
06-10 17:30:30.223: E/Vitamio[4.2.1][Player](25156): NO SUBTITLE DATA FOUND.

I saw error in my log.
06-10 17:26:24.473: E/Vitamio[4.2.1][Player](22510): FIND_NAME_SYM vvo, render_yuv

**Comment by MythodeaLoL** [comment]
Same problem, you fixed it @kietcao ?

**Comment by kietcao** [comment]
Yes, I made own subtitle with vitamio and another player. It can use for any player. @MelissaTaylor, you want to make it?

**Comment by MythodeaLoL** [comment]
Yes, but only for vitamio, no other players . @kietcao
