### ISSUE TITLE
Why VideoView setVideoUri(Uri uri,Headers headers) doesn't work?

### ISSUE THREAD

**Issue by xiaofans** [yixia/VitamioBundle#177]
I want to add a Referer or other stuff,but do not work.

**Comment by Anbu312** [comment]
Map<String, String> headers = new HashMap<String, String>();
            headers.put("headers", "Referer:xxx\r\n");
            headers.put("Cookie","Cookie:CloudFront-Signature=xx; Domain=xx; Path=xx);
            headers.put("Cookie","Cookie:xx; Domain=xx; Path=xx");
            headers.put("Cookie","CloudFront-Key-Pair-Id=xx; Domain=xx; Path=XX");

            mediaPlayer = new MediaPlayer();
            mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
            mediaPlayer.setDataSource(MediaPlayerService.this, Uri.parse("URL"),headers);
            mediaPlayer.prepare();
            mediaPlayer.start();

I'm playing audio like this but it throughs only error. Audio not getting played

**Comment by Vaishnavi-optisol** [comment]
Map headers = new HashMap();
headers.put("Cookie","CloudFront-Signature=xx; Domain=xx; Path=xx);
headers.put("Cookie","CloudFront-Policy=xx; Domain=xx; Path=xx");
headers.put("Cookie","CloudFront-Key-Pair-Id=xx; Domain=xx; Path=XX");

```
    mediaPlayer = new MediaPlayer();
    mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
    mediaPlayer.setDataSource(MediaPlayerService.this, Uri.parse("URL"),headers);
    mediaPlayer.prepare();
    mediaPlayer.start();
```

I'm playing audio like this but it throughs only error. Audio not getting played

**Comment by MythodeaLoL** [comment]
@Vaishnavi-optisol u need to **add** `\r\n` at end, see examples man =)

https://github.com/yixia/VitamioBundle/issues/177#issuecomment-48872226 exemples

**Comment by Vaishnavi-optisol** [comment]
@FloridaStream : Thanks for your response I also tried in the way you mentioned above like this.

Map<String, String> headers = new HashMap<String, String>();
            headers.put("Cookie","CloudFront-Signature=xx\r\n");
            headers.put("Cookie","CloudFront-Policy=xx\r\n");
            headers.put("Cookie","CloudFront-Key-Pair-Id=xx\r\n");
            headers.put("Cookie","Domain=xx\r\n");
            headers.put("Cookie","Path=xx\r\n");

Still no luck. I even tried like -  headers.put("headers","Cookie:CloudFront-Signature=xx; Domain=xx\r\n"); and
headers.put("headers","Cookie:CloudFront-Signature=xx\r\n; Domain=xx\r\n");

Thanks in advance

**Comment by Vaishnavi-optisol** [comment]
@FloridaStream 

Thanks for the support. It works now for me I tried like below:
headers.put("Cookie","CloudFront-Policy=xx; CloudFront-Signature=xx; Domain=xx; Path=xx\r\n");
