### ISSUE TITLE
How to set header for play video?

### ISSUE THREAD

**Issue by vuhung3990** [yixia/VitamioBundle#219]
my code: 
headers = new HashMap<String, String>();
headers.put("aaa", "abcxyz");
mVideoView.setVideoURI(uri, headers);

i tested on browser work well(firefox, chrome) but not work with vitamio. please tell me how to solve problem, thank you

**Comment by guoyoujin** [comment]
Why do I use headers.put("Referer", "http://guoyoujin.com\r\n")  is invalid, can you put the code posted in more detail

**Comment by velpukondaramesh** [comment]
#vuhung3990
how to tested on browser url with header please can u exaplin me?
