### ISSUE TITLE
what is wrong?

### ISSUE THREAD

**Issue by alexliyu** [yixia/VitamioBundle#22]
the logcat show:
07-27 22:48:22.152: E/OMXCodec(18763): [OMX.google.h264.decoder] Codec lied about its buffer size requirements, sending a buffer larger than the originally advertised size in FILL_BUFFER_DONE!

09-27 15:52:05.928: D/Vitamio[Player](7721): CPU implementer:0x41
09-27 15:52:05.928: D/Vitamio[Player](7721): Serial:0541ce82575548488071825016236784
09-27 15:52:05.938: D/Vitamio[Player](7721): CPU architecture:7
09-27 15:52:05.948: D/Vitamio[Player](7721): Hardware:sun4i
09-27 15:52:05.948: D/Vitamio[Player](7721): CPU revision:2
09-27 15:52:05.958: D/Vitamio[Player](7721): CPU variant:0x3
09-27 15:52:05.958: D/Vitamio[Player](7721): CPU part:0xc08
09-27 15:52:05.968: D/Vitamio[Player](7721): Revision:0000
09-27 15:52:05.968: D/Vitamio[Player](7721): BogoMIPS:1001.88
09-27 15:52:05.978: D/Vitamio[Player](7721): Features:swp half thumb fastmult vfp edsp neon vfpv3
09-27 15:52:05.978: D/Vitamio[Player](7721): Processor:ARMv7 Processor rev 2 (v7l)
09-27 15:52:05.988: D/Vitamio[Player](7721): CPU architecture: 7
09-27 15:52:05.998: D/Vitamio[Player](7721): GET CPU FATURE: V5TE V6 VFP V7A VFPV3 NEON 
09-27 15:52:05.998: D/dalvikvm(7721): Trying to load lib /data/data/io.vov.vitamio.demo/lib/libvinit.so 0x41044ed0
09-27 15:52:05.998: D/dalvikvm(7721): Added shared lib /data/data/io.vov.vitamio.demo/lib/libvinit.so 0x41044ed0
09-27 15:52:06.028: I/Vitamio[Player](7721): isNativeLibsInited, APP VERSION: 2, Vitamio Library version: 2
09-27 15:52:06.218: D/libEGL(7721): loaded /system/lib/egl/libGLES_android.so
09-27 15:52:06.228: D/libEGL(7721): loaded /system/lib/egl/libEGL_mali.so
09-27 15:52:06.238: D/libEGL(7721): loaded /system/lib/egl/libGLESv1_CM_mali.so
09-27 15:52:06.238: D/libEGL(7721): loaded /system/lib/egl/libGLESv2_mali.so
09-27 15:52:06.268: D/OpenGLRenderer(7721): Enabling debug mode 0
09-27 15:52:12.658: D/OpenGLRenderer(7721): Flushing caches (mode 0)
09-27 15:52:13.938: I/Vitamio[Player](7721): isNativeLibsInited, APP VERSION: 2, Vitamio Library version: 2
09-27 15:52:13.998: D/SurfaceView(7721): pckname = io.vov.vitamio.demo
09-27 15:52:14.088: I/SurfaceView(7721): Changes: creating=true format=true size=true visible=true mLeft=-1 mTop =-1 mLocation[0]=0 mLocation[1]=56 left=true top=true
09-27 15:52:14.088: I/SurfaceView(7721): Cur surface: Surface(name=null, identity=-1)
09-27 15:52:14.098: I/SurfaceView(7721): New surface: Surface(name=null, identity=1171), vis=true, frame=Rect(0, 56 - 1280, 720)
09-27 15:52:14.098: I/SurfaceView(7721): visibleChanged -- surfaceCreated
09-27 15:52:14.098: D/MediaPlayerDemo(7721): surfaceCreated called
09-27 15:52:14.108: I/Vitamio[Player](7721): LIB ROOT: /data/data/io.vov.vitamio.demo/libs/
09-27 15:52:14.108: D/dalvikvm(7721): Trying to load lib /data/data/io.vov.vitamio.demo/libs/libstlport_shared.so 0x41044ed0
09-27 15:52:14.108: D/dalvikvm(7721): Added shared lib /data/data/io.vov.vitamio.demo/libs/libstlport_shared.so 0x41044ed0
09-27 15:52:14.108: D/dalvikvm(7721): No JNI_OnLoad found in /data/data/io.vov.vitamio.demo/libs/libstlport_shared.so 0x41044ed0, skipping init
09-27 15:52:14.108: D/dalvikvm(7721): Trying to load lib /data/data/io.vov.vitamio.demo/libs/libvplayer.so 0x41044ed0
09-27 15:52:14.108: D/dalvikvm(7721): Added shared lib /data/data/io.vov.vitamio.demo/libs/libvplayer.so 0x41044ed0
09-27 15:52:14.118: I/Vitamio[Player](7721): Copyright (c) YIXIA (http://yixia.com).
09-27 15:52:14.118: I/Vitamio[Player](7721): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
09-27 15:52:14.118: I/Vitamio[Player](7721): LOAD FFMPEG START: /data/data/io.vov.vitamio.demo/libs/libffmpeg.so
09-27 15:52:14.128: I/Vitamio[Player](7721): LOAD FFMPEG END: /data/data/io.vov.vitamio.demo/libs/libffmpeg.so
09-27 15:52:14.128: I/Vitamio[Player](7721): LOAD VVO START: /data/data/io.vov.vitamio.demo/libs/libvvo.9.so
09-27 15:52:14.128: E/Vitamio[Player](7721): FIND_NAME_SYM vvo, render_yuv
09-27 15:52:14.128: I/Vitamio[Player](7721): LOAD VVO END: /data/data/io.vov.vitamio.demo/libs/libvvo.9.so
09-27 15:52:14.128: I/Vitamio[Player](7721): LOAD VAO START: /data/data/io.vov.vitamio.demo/libs/libvao.0.so
09-27 15:52:14.128: I/Vitamio[Player](7721): LOAD VAO END: /data/data/io.vov.vitamio.demo/libs/libvao.0.so
09-27 15:52:14.128: I/Vitamio[Player](7721): LOAD OMX START: /data/data/io.vov.vitamio.demo/libs/libOMX.14.so
09-27 15:52:14.138: I/Vitamio[Player](7721): LOAD OMX END: /data/data/io.vov.vitamio.demo/libs/libOMX.14.so
09-27 15:52:14.138: I/Vitamio[Player](7721): VPLAYER INIT BEGIN
09-27 15:52:14.138: I/Vitamio[Player](7721): Copyright (c) YIXIA (http://yixia.com).
09-27 15:52:14.138: I/Vitamio[Player](7721): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
09-27 15:52:14.138: I/Vitamio[Player](7721): Application package name: io.vov.vitamio.demo
09-27 15:52:14.138: D/Vitamio[Player](7721): RENDER RGB
09-27 15:52:14.158: D/Vitamio[Player](7721): THREAD NOTIFY START
09-27 15:52:14.178: I/Vitamio[Player](7721): VPLAYER INIT END
09-27 15:52:14.178: I/Vitamio[Player](7721): Copyright (c) YIXIA (http://yixia.com).
09-27 15:52:14.178: I/Vitamio[Player](7721): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
09-27 15:52:14.178: I/Vitamio[Player](7721): Application package name: io.vov.vitamio.demo
09-27 15:52:14.178: D/Vitamio[Player](7721): SURFACE INIT OK
09-27 15:52:14.178: I/Vitamio[Player](7721): Copyright (c) YIXIA (http://yixia.com).
09-27 15:52:14.178: I/Vitamio[Player](7721): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
09-27 15:52:14.178: I/Vitamio[Player](7721): Application package name: io.vov.vitamio.demo
09-27 15:52:14.178: D/Vitamio[Player](7721): SURFACE INIT OK
09-27 15:52:14.178: D/Vitamio[Player](7721): prepare
09-27 15:52:14.178: I/Vitamio[Player](7721): PREPARE SIG: 0
09-27 15:52:14.178: I/Vitamio[Player](7721): THREAD PREPARE START
09-27 15:52:14.188: I/Vitamio[Player](7721): THREAD PREPARE ATTACHED
09-27 15:52:14.188: I/Vitamio[Player](7721): Copyright (c) YIXIA (http://yixia.com).
09-27 15:52:14.188: I/Vitamio[Player](7721): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
09-27 15:52:14.188: I/Vitamio[Player](7721): OPEN FILE /mnt/sdcard/33.mp4
09-27 15:52:14.278: D/Vitamio[Player](7721): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/sdcard/33.mp4':
09-27 15:52:14.278: D/Vitamio[Player](7721):   Metadata:
09-27 15:52:14.278: D/Vitamio[Player](7721):     major_brand     : 
09-27 15:52:14.278: D/Vitamio[Player](7721): isom
09-27 15:52:14.278: D/Vitamio[Player](7721):     minor_version   : 
09-27 15:52:14.278: D/Vitamio[Player](7721): 1
09-27 15:52:14.278: D/Vitamio[Player](7721):     compatible_brands: 
09-27 15:52:14.278: D/Vitamio[Player](7721): isomavc1
09-27 15:52:14.288: D/Vitamio[Player](7721):     creation_time   : 
09-27 15:52:14.288: D/Vitamio[Player](7721): 2010-10-31 11:57:00
09-27 15:52:14.288: D/Vitamio[Player](7721):   Duration: 
09-27 15:52:14.288: D/Vitamio[Player](7721): 00:04:13.09
09-27 15:52:14.288: D/Vitamio[Player](7721): , start: 
09-27 15:52:14.288: D/Vitamio[Player](7721): 0.000000
09-27 15:52:14.288: D/Vitamio[Player](7721): , bitrate: 
09-27 15:52:14.288: D/Vitamio[Player](7721): 2132 kb/s
09-27 15:52:14.298: D/Vitamio[Player](7721):     Stream #0:0
09-27 15:52:14.298: D/Vitamio[Player](7721): (und)
09-27 15:52:14.298: D/Vitamio[Player](7721): : Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 720x480 [SAR 40:33 DAR 20:11], 1999 kb/s
09-27 15:52:14.298: D/Vitamio[Player](7721): , SAR 109:90 DAR 109:60
09-27 15:52:14.298: D/Vitamio[Player](7721): , 29.97 fps
09-27 15:52:14.298: D/Vitamio[Player](7721): , 29.97 tbr
09-27 15:52:14.298: D/Vitamio[Player](7721): , 30k tbn
09-27 15:52:14.298: D/Vitamio[Player](7721): , 59.94 tbc
09-27 15:52:14.298: D/Vitamio[Player](7721):     Metadata:
09-27 15:52:14.298: D/Vitamio[Player](7721):       creation_time   : 
09-27 15:52:14.298: D/Vitamio[Player](7721): 2010-10-31 11:57:00
09-27 15:52:14.298: D/Vitamio[Player](7721):       handler_name    : 
09-27 15:52:14.298: D/Vitamio[Player](7721): GPAC ISO Video Handler
09-27 15:52:14.298: D/Vitamio[Player](7721):     Stream #0:1
09-27 15:52:14.298: D/Vitamio[Player](7721): (und)
09-27 15:52:14.298: D/Vitamio[Player](7721): : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
09-27 15:52:14.298: D/Vitamio[Player](7721):     Metadata:
09-27 15:52:14.298: D/Vitamio[Player](7721):       creation_time   : 
09-27 15:52:14.298: D/Vitamio[Player](7721): 2010-10-31 11:57:02
09-27 15:52:14.298: D/Vitamio[Player](7721):       handler_name    : 
09-27 15:52:14.298: D/Vitamio[Player](7721): GPAC ISO Audio Handler
09-27 15:52:14.298: I/Vitamio[Player](7721): METADATA: isom1isomavc12010-10-31 11:57:00
09-27 15:52:14.298: I/Vitamio[Player](7721): META AUDIO: 1. und. 2010-10-31 11:57:02, META SUBTITLE: 
09-27 15:52:14.298: D/Vitamio[Player](7721): FIND CODEC_ID 86018
09-27 15:52:14.298: I/Vitamio[Player](7721): OOPS: ONLY 1
09-27 15:52:14.328: D/Vitamio[Player](7721): OPEN CODEC aac
09-27 15:52:14.328: I/Vitamio[Player](7721): OPEN STREAM AUDIO BEGIN
09-27 15:52:14.328: I/Vitamio[Player](7721): Copyright (c) YIXIA (http://yixia.com).
09-27 15:52:14.328: I/Vitamio[Player](7721): THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
09-27 15:52:14.328: I/Vitamio[Player](7721): Application package name: io.vov.vitamio.demo
09-27 15:52:14.328: I/Vitamio[Player](7721): 2, 44100, 0
09-27 15:52:14.338: I/Vitamio[Player](7721): OPEN STREAM AUDIO END
09-27 15:52:14.338: D/Vitamio[Player](7721): SURFACE RELEASEED OK
09-27 15:52:14.338: D/Vitamio[Player](7721): THREAD AUDIO_DECODE START
09-27 15:52:14.358: I/OMXCodec(7721): [OMX.google.h264.decoder] AVC profile = 77 (Main), level = 30
09-27 15:52:14.358: D/Vitamio[Player](7721): THREAD AUDIO_OUTPUT START
09-27 15:52:14.358: I/OMXCodec(7721): [OMX.google.h264.decoder] video dimensions are 320 x 240
09-27 15:52:14.358: I/OMXCodec(7721): [OMX.google.h264.decoder] Crop rect is 320 x 240 @ (0, 0)
09-27 15:52:14.368: E/Vitamio[Player](7721): Unknown video color format: 32315659
09-27 15:52:14.368: A/OMXCodec(7721): frameworks/base/media/libstagefright/OMXCodec.cpp:1594 CHECK(mState == LOADED || mState == ERROR || mState == LOADED_TO_IDLE) failed.
09-27 15:52:14.368: A/libc(7721): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)
09-27 15:52:14.448: D/dalvikvm(7721): GC_CONCURRENT freed 195K, 5% free 6809K/7111K, paused 2ms+13ms
09-27 15:52:15.418: W/AudioTrack(7721): obtainBuffer() track 0x292bf8 disabled, restarting
09-27 15:52:16.498: W/AudioTrack(7721): obtainBuffer() track 0x292bf8 disabled, restarting
09-27 15:52:17.578: W/AudioTrack(7721): obtainBuffer() track 0x292bf8 disabled, restarting
09-27 15:52:18.658: W/AudioTrack(7721): obtainBuffer() track 0x292bf8 disabled, restarting
09-27 15:52:19.738: W/AudioTrack(7721): obtainBuffer() track 0x292bf8 disabled, restarting
09-27 15:52:20.828: W/AudioTrack(7721): obtainBuffer() track 0x292bf8 disabled, restarting
09-27 15:52:22.228: D/Vitamio[Player](7753): CPU implementer:0x41
09-27 15:52:22.248: D/Vitamio[Player](7753): Serial:0541ce82575548488071825016236784
09-27 15:52:22.248: D/Vitamio[Player](7753): CPU architecture:7
09-27 15:52:22.258: D/Vitamio[Player](7753): Hardware:sun4i
09-27 15:52:22.258: D/Vitamio[Player](7753): CPU revision:2
09-27 15:52:22.258: D/Vitamio[Player](7753): CPU variant:0x3
09-27 15:52:22.258: D/Vitamio[Player](7753): CPU part:0xc08
09-27 15:52:22.258: D/Vitamio[Player](7753): Revision:0000
09-27 15:52:22.258: D/Vitamio[Player](7753): BogoMIPS:1001.88
09-27 15:52:22.268: D/Vitamio[Player](7753): Features:swp half thumb fastmult vfp edsp neon vfpv3
09-27 15:52:22.268: D/Vitamio[Player](7753): Processor:ARMv7 Processor rev 2 (v7l)
09-27 15:52:22.268: D/Vitamio[Player](7753): CPU architecture: 7
09-27 15:52:22.278: D/Vitamio[Player](7753): GET CPU FATURE: V5TE V6 VFP V7A VFPV3 NEON 
09-27 15:52:22.278: D/dalvikvm(7753): Trying to load lib /data/data/io.vov.vitamio.demo/lib/libvinit.so 0x410457f8
09-27 15:52:22.278: D/dalvikvm(7753): Added shared lib /data/data/io.vov.vitamio.demo/lib/libvinit.so 0x410457f8
09-27 15:52:22.298: I/Vitamio[Player](7753): isNativeLibsInited, APP VERSION: 2, Vitamio Library version: 2

**Comment by ghost** [comment]
Hello everyone,
How can we flush the buffer once It gets full? Bcoz Once It gets full, It starts increasing the latency.
