### ISSUE TITLE
Vitamio Doesn't Play Swf RTMP Urls 

### ISSUE THREAD

**Issue by tichs** [yixia/VitamioBundle#23]
I tried playing a link in vitamio but it didn't work, I used it on my PC and it opened well.

**Comment by saveme925** [comment]
Hi, I am also getting same problem. It just freeze and then crash. How can I add AVOptions to play this stream. Here is my stream URL
"rtmp://oregon.owvideo.greenjobinterview.net/oneway/_definst_/intro/361/2329_1422050345864";
