### ISSUE TITLE
OpenSSL Google Play ALERT

### ISSUE THREAD

**Issue by mkiisoft** [yixia/VitamioBundle#235]
I have receive this email from Google in the apps that I'm using Vitamio:

Hello,

One or more of your apps is running an outdated version of OpenSSL, which has multiple security vulnerabilities. You should update OpenSSL to versions 1.0.1h, 1.0.0m y 0.9.8za as soon as possible. For more information about the most recent security vulnerability in OpenSSL, please see http://www.openssl.org/news/secadv_20140605.txt.

Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered “dangerous products” and subject to removal from Google Play.

Regards,

Google Play Team

©2014 Google Inc. 1600 Amphitheatre Parkway Mountain View, CA 94043

Email preferences: You have received this mandatory email service announcement to update you about important changes to your Google Play account.

Any way to fix this? I don't want to lose my apps. Does anyone have .so files with that fix it?

**Comment by mkiisoft** [comment]
@mhcpan I get the notification from Goggle AGAIN! Any news about an update?! cc @crossle

**Comment by crossle** [comment]
Sorry, Update this week.

**Comment by mhcpan** [comment]
Great news. @mkiisoft,  I also received openssl alert from Google Play again a few days ago. It good that crosse confirm the update.

**Comment by AbelValdez** [comment]
Hi i have the same issue with Vitamio lib, can you put the link with the issue fixed please..

Regards!

**Comment by crossle** [comment]
https://github.com/yixia/VitamioBundle/commit/a216a0791eb250a117845e105c42e49b08b5244f

**Comment by rendev** [comment]
Hello @crossle, could you please version with updated version of OpenSSL for intel processors too?
After updated library, i had a crash that "Native libs libffmpeg.so not exists!" for asus zenfone 6.

**Comment by josemoreno10** [comment]
hello @crossle I need to update Vitamio with updated version of OpenSSL but I do not know how 4.2.2 version 4.2.6 I do not find, you help me, I have the same warning from google play

"One or more of your apps is running an outdated version of OpenSSL, which has multiple security vulnerabilities. You should update OpenSSL as soon as possible. For more information about the most recent security vulnerability in OpenSSL, please see http://www.openssl.org/news/secadv_20140605.txt.

Please note, while it's unclear whether these specific issues affect your application, applications with vulnerabilities that expose users to risk of compromise may be considered “dangerous products” and subject to removal from Google Play.

Regards,

Google Play Team"

**Comment by crossle** [comment]
see https://github.com/yixia/VitamioBundle/commit/a216a0791eb250a117845e105c42e49b08b5244f
