### ISSUE TITLE
Can you stream RTMP using Vitamio?

### ISSUE THREAD

**Issue by lfdversluis** [yixia/VitamioBundle#256]
I want to capture the android camera stream and send it to a server using the RTMP protocol. Is this possible with Vitamio?

If you can, is there some documentation, example or other pointers to this? I've searched around but unable to find something close.

**Comment by allouch89** [comment]
Yes you can, all i can say it that you need to use a VideoView, Media Player and Media Controller.
Maybe this can help you expand your search.

**Comment by lfdversluis** [comment]
I ended up using another library, but thanks

**Comment by allouch89** [comment]
Do you mind telling me what library? Vitamio isn't work so great for my devices.

**Comment by lfdversluis** [comment]
I am using javaCV now, the java ported version of opencv.

**Comment by alinoman12** [comment]
i want to develop android app which will view live streaming of ip camera ...any one can guide plz..?
