### ISSUE TITLE
Vitamio with Token, securetoken support for protected videos (secureTokenResponse)

### ISSUE THREAD

**Issue by MythodeaLoL** [yixia/VitamioBundle#283]
###### Samples:

```
            path = "rtmp://8.8.8.8/live/";
            options = new HashMap<String, String>();
            options.put("rtmp_app", "live");
            options.put("rtmp_swfurl", "http://www.example.com.com/mediaplayer.swf");
            options.put("rtmp_playpath", "bigbuckbunny");
            options.put("rtmp_pageurl", "http://www.example.com/protected_stream.html");
            options.put("token", "fg5ASTACK_d8g#$#!@");
```
###### or

```
options.put("rtmp_token", "fg5AAf4gd8g#$#!@");
```
###### On flash is called:

```
this._connection.call("secureTokenResponse", null, TEA.decrypt(evt.info.secureToken, "fg5ASTACK_d8g#$#!@"));
```
### Please compile librtmp (rtmpdump) with vitamio. I can not do it, is something many need (token support)

Tks man. Good project, but need upgrade. Waiting reply.

@crossle =)
Ref: https://github.com/mekya/Vitamio-with-librtmp (dont work for me, outdated)
:boom:  Other users, please post here to support the cause.

**Comment by MythodeaLoL** [comment]
I cant compile, closing now. =(

**Comment by khaintt** [comment]
@FloridaStream can you show me how to solve this issue. I had same issue too. Thanks so much.

**Comment by MythodeaLoL** [comment]
@khaintt i cant compile, i need full sdk to compile, i cant find it, sorry. =(

**Comment by khaintt** [comment]
Thanks Ranny @FloridaStream . We should try another approach :+1:
