### ISSUE TITLE
Differences between MediaPlayerDemo and VideoViewDemo?

### ISSUE THREAD

**Issue by MythodeaLoL** [yixia/VitamioBundle#287]
<b>Hello</b> @crossle and all the collaborators,
I'm not familiar with MediaPlayerDemo, what are the differences between the two? What can I do with one that can not do with the other?

**Comment by MelissaTaylor** [comment]
The project is stopped? humm

**Comment by crossle** [comment]
@MelissaTaylor i quit this project
