### ISSUE TITLE
Missing lib

### ISSUE THREAD

**Issue by GiuseppeIuculano** [yixia/VitamioBundle#3]
Hi,

I'm trying VitamioBundle, but i got this when I try to play a video:

D/Vitamio (12035): GET CPU FATURE: V5TE V6 VFP V7A VFPV3 NEON 
D/dalvikvm(12035): Trying to load lib /data/data/com.iuculano.allmytv/lib/libvinit.so 0x4185a0d0
D/dalvikvm(12035): Added shared lib /data/data/com.iuculano.allmytv/lib/libvinit.so 0x4185a0d0
I/Vitamio (12035): LIB ROOT: null
D/dalvikvm(12035): Trying to load lib nulllibstlport_shared.so 0x4185a0d0
D/dalvikvm(11019): GC_CONCURRENT freed 1465K, 24% free 14909K/19527K, paused 2ms+8ms, total 128ms
D/dalvikvm(11019): WAIT_FOR_CONCURRENT_GC blocked 97ms
E/Vitamio (12035): Error loading libs
E/Vitamio (12035): java.lang.UnsatisfiedLinkError: Cannot load library: load_library[1093]: Library 'nulllibstlport_shared.so' not found
E/Vitamio (12035):  at java.lang.Runtime.load(Runtime.java:340)
E/Vitamio (12035):  at java.lang.System.load(System.java:521)
E/Vitamio (12035):  at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:100)
E/Vitamio (12035):  at io.vov.vitamio.MediaPlayer.<init>(MediaPlayer.java:78)
E/Vitamio (12035):  at io.vov.vitamio.widget.VideoView.openVideo(VideoView.java:221)
E/Vitamio (12035):  at io.vov.vitamio.widget.VideoView.access$29(VideoView.java:209)
E/Vitamio (12035):  at io.vov.vitamio.widget.VideoView$9.surfaceCreated(VideoView.java:461)
E/Vitamio (12035):  at android.view.SurfaceView.updateWindow(SurfaceView.java:543)
E/Vitamio (12035):  at android.view.SurfaceView.access$000(SurfaceView.java:81)
E/Vitamio (12035):  at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:169)
E/Vitamio (12035):  at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:671)
E/Vitamio (12035):  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1820)
E/Vitamio (12035):  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
E/Vitamio (12035):  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
E/Vitamio (12035):  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
E/Vitamio (12035):  at android.view.Choreographer.doCallbacks(Choreographer.java:555)
E/Vitamio (12035):  at android.view.Choreographer.doFrame(Choreographer.java:525)
E/Vitamio (12035):  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
E/Vitamio (12035):  at android.os.Handler.handleCallback(Handler.java:615)
E/Vitamio (12035):  at android.os.Handler.dispatchMessage(Handler.java:92)
E/Vitamio (12035):  at android.os.Looper.loop(Looper.java:137)
E/Vitamio (12035):  at android.app.ActivityThread.main(ActivityThread.java:4745)
E/Vitamio (12035):  at java.lang.reflect.Method.invokeNative(Native Method)
E/Vitamio (12035):  at java.lang.reflect.Method.invoke(Method.java:511)
E/Vitamio (12035):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/Vitamio (12035):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/Vitamio (12035):  at dalvik.system.NativeStart.main(Native Method)
W/dalvikvm(12035): No implementation found for native Lio/vov/vitamio/MediaPlayer;.unloadOMX_native:()V
D/AndroidRuntime(12035): Shutting down VM
W/dalvikvm(12035): threadid=1: thread exiting with uncaught exception (group=0x40dcc300)

**Comment by sohayb** [comment]
@crossle I'm having the same issue @reyou is talking about, eventhough all is working until I try to change the data source
unloadOMX failed java.lang.UnsatisfiedLinkError: Native method not found: io.vov.vitamio.MediaPlayer.unloadOMX_native:()V

**Comment by xlee00** [comment]
Must call Vitamio.isInitialized(this);
after super.onCreate();
but not onStart();
Must call Vitamio.isInitialized(this);
after super.onCreate();
but not onStart();
