### ISSUE TITLE
Vitamio not working in x86 emulator

### ISSUE THREAD

**Issue by mafshin** [yixia/VitamioBundle#31]
I have to test my vitamio-powered app with different devices but unfortunately the vitamio library can't be initialized in any emulator (x86, ARM, Android 2.3, 4.2 ,..... )

It says can't find libffmpeg.so.

Do you have any comment on this?

**Comment by rahulqv** [comment]
Vitamio doesn't work with Intel based processors. It works only with ARMv6 and up processors. But peoples reported it works with snapdragon too.
