### ISSUE TITLE
intel support (asus zenpad)

### ISSUE THREAD

**Issue by zaferaydn** [yixia/VitamioBundle#322]
hello,
I have asus zenpad tablet. it is P023 model. It says "intel inside", so I understand it has intel CPU. 
My android application uses Vitamio library. In asus zenpad(intel) tablet, my android application fails when i try to play a rtsp stream from ip camera. In logs i see "Native libs libffmpeg.so not exists!" error message. What is more, after this error i get the following exception and my application closes:

java.lang.UnsatisfiedLinkError: dlopen failed: library "/data/data/com.mycompany.myapplication/libs/libstlport_shared.so" not found

 Same application works OK in arm based tablet and phones(galaxy nexus, nexus 10, smsung S3 mini vs.) What is this missing libffmpeg.so library and how can i install it in my tablet which has intel cpu?

**Comment by MythodeaLoL** [comment]
Try rename libarm.so to libarm in vitamio files, io.vov.vitamio ... search for libarm.so

**Comment by zaferaydn** [comment]
I did that. It did not solve. The error message complains about not finding libffmpeg.so and ibstlport_shared.so. should i find these libraries somewhere and put it libs folder of my project? Anyone tested vitamio with an intel processor like my asus zenpad?

**Comment by longcworld** [comment]
I got the same problem !!!  I didn't solve either,but everything is ok when i run the demo

**Comment by MythodeaLoL** [comment]
I wanted to help in some way, there is some way to emulate that in some android emulator to reproduce this error? 

<i>You could test it only with a code sample?</i>

@zaferaydn @longcworld

**Comment by zaferaydn** [comment]
Hello floridaStream,
Thank you for your attention. There is demo application of Vitamio in https://github.com/yixia/VitamioBundle/tree/master/vitamio-sample . 
I also tested with this demo application and I could not play rtsp stream on asus zenpad. I could play the same stream link on Samsung Galaxy Nexus. 
If you want to try demo application, you can go to "MediaPlayer / Play Streaming Video" and put rtsp link.
Note that demo appllcation does not crash like my application does. But It can not show the video neither.

**Comment by MythodeaLoL** [comment]
you need this to play `rtsp`

```
HashMap<String, String> options = new HashMap<String, String>();
options.put("rtsp_transport", "tcp"); // udp
mediaPlayer.setDataSource(path, options);
```

see wiki https://github.com/yixia/VitamioBundle/wiki/Use-FFmpeg-AVOption-in-Vitamio-4.1.0

try this @zaferaydn

**Comment by zaferaydn** [comment]
Hello @FloridaStream 

I tried but no success. It still gives the same exception and crash. But I can you inform you that i get also the following exception logs. Maybe it can not find a needed library and can not find its native method.

Maybe the core of the problem is initialization step. I guess it can not load some libraries that it needs when playing RTSP.

```
E/art: No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)

E/Vitamio[Player]: unloadOMX failed java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.unloadOMX_native() (tried Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native and Java_io_vov_vitamio_MediaPlayer_unloadOMX_1native__)

E/art: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)

E/AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void io.vov.vitamio.MediaPlayer.native_init() (tried Java_io_vov_vitamio_MediaPlayer_native_1init and Java_io_vov_vitamio_MediaPlayer_native_1init__)
```

**Comment by MythodeaLoL** [comment]
Hi @zaferaydn =)
Are you using all the necessary files?

See my settings:
<i>Vitamio files</i>
src\main\java\io\vov\vitamio <i>files</i>
https://github.com/yixia/VitamioBundle/tree/master/vitamio/src/io/vov/vitamio

<i>My application</i>
src\main\java\myapp <i>VideoViewDemo.java file</i>
https://github.com/yixia/VitamioBundle/blob/master/vitamio-sample/src/io/vov/vitamio/demo/VideoViewDemo.java

<i>Libarm</i>
src\main\res\raw <i>libarm.so file</i>
Try this
https://github.com/yixia/VitamioBundle/tree/master/dist/arm_x86_mips
or this
https://github.com/yixia/VitamioBundle/tree/master/vitamio/res/raw <b>(updated)</b>

<i>CPU</i>

```
src\main\jniLibs 
                ->armeabi\
                ->armeabi-v7a\
                ->mips\
                ->x86\
```

<i>Gradle</i>

```
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"
...
```

**Comment by zaferaydn** [comment]
Hello Ranny,

Finally it worked! I replaced the libarm.so library with the following link:

https://github.com/yixia/VitamioBundle/blob/master/dist/arm_x86_mips/res/raw/libarm.so

This libarm.so file 17MB sized, bigger than I was using. So I guess it contains the necessary libs which my CPU needs. 

An other thing, I was having this library only under raw folder of my Vitamio module referances from my project. Now I put this library also in my project's raw folder. Now when vitamio initializes the libraries it uses the libarm.so library from my project's raw folder.

This solution is nice but there is a sideeffect. The default libarm.so library was about 8 MB, now the updated library is around 17 MB. So this makes my apk size 9 MB more! I have to find some methods to minimize the size of my application(apk). I saw there is Vitamio online version(the following link:)

https://github.com/yixia/VitamioBundle/wiki/How-to-use-Vitamio-4.2.0-online-version%3F

I will analize this online version and I am going to find a way for downloading the neccessary libraries after installing the apk. If you already have some ideas about it, please share. 

Very pleased for your help. Thank you.

@FloridaStream @longcworld

**Comment by zaferaydn** [comment]
Hello Ranny,
I created an other issue for using online version of Vitamio libraries:
https://github.com/yixia/VitamioBundle/issues/328
I close this issue. 
Thanks.
@FloridaStream
