### ISSUE TITLE
cannot play video

### ISSUE THREAD

**Issue by qetchx** [yixia/VitamioBundle#324]
"sorry, this video cannot be played"
i recved this message, samsung gallexy note 2(SAMSUNG-SGH-I317)
i check my rtmp(rtmp://106.248.243.130:8080/live/ht_01&autoplay=true&playerID=player-container) link is welldone 
but my android app is not working
and other example link is not working too

how can i solve this problem?
here is my logcat massage

12-02 02:50:40.989 21762-21762/? D/dalvikvm: Late-enabling CheckJNI
12-02 02:50:41.044 21762-21762/? E/Trace: error opening trace file: No such file or directory (2)
12-02 02:50:41.109 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
12-02 02:50:41.109 21762-21762/com.example.qeantx_pc.test2 I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
12-02 02:50:41.109 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to resolve interface method 18050: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
12-02 02:50:41.109 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
12-02 02:50:41.114 21762-21762/com.example.qeantx_pc.test2 I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
12-02 02:50:41.114 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to resolve interface method 18054: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
12-02 02:50:41.114 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
12-02 02:50:41.139 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: Trying to load lib /data/data/com.example.qeantx_pc.test2/lib/libvinit.so 0x41f8bd20
12-02 02:50:41.139 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: Added shared lib /data/data/com.example.qeantx_pc.test2/lib/libvinit.so 0x41f8bd20
12-02 02:50:41.169 21762-21764/com.example.qeantx_pc.test2 D/dalvikvm: GC_CONCURRENT freed 251K, 9% free 12378K/13575K, paused 2ms+1ms, total 18ms
12-02 02:50:41.179 21762-21762/com.example.qeantx_pc.test2 I/dalvikvm: Could not find method android.view.ViewGroup.onRtlPropertiesChanged, referenced from method android.support.v7.widget.Toolbar.onRtlPropertiesChanged
12-02 02:50:41.179 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to resolve virtual method 17946: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
12-02 02:50:41.179 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: VFY: replacing opcode 0x6f at 0x0007
12-02 02:50:41.184 21762-21762/com.example.qeantx_pc.test2 I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
12-02 02:50:41.184 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to resolve virtual method 456: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
12-02 02:50:41.184 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
12-02 02:50:41.184 21762-21762/com.example.qeantx_pc.test2 I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
12-02 02:50:41.184 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to resolve virtual method 478: Landroid/content/res/TypedArray;.getType (I)I
12-02 02:50:41.184 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
12-02 02:50:41.189 21762-21762/com.example.qeantx_pc.test2 I/dalvikvm: Could not find method android.widget.LinearLayout$LayoutParams.<init>, referenced from method android.support.design.widget.AppBarLayout$LayoutParams.<init>
12-02 02:50:41.189 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to resolve direct method 18569: Landroid/widget/LinearLayout$LayoutParams;.<init> (Landroid/widget/LinearLayout$LayoutParams;)V
12-02 02:50:41.189 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: VFY: replacing opcode 0x70 at 0x0000
12-02 02:50:41.189 21762-21762/com.example.qeantx_pc.test2 I/dalvikvm: Could not find method android.widget.LinearLayout$LayoutParams.<init>, referenced from method android.support.design.widget.AppBarLayout$LayoutParams.<init>
12-02 02:50:41.189 21762-21762/com.example.qeantx_pc.test2 W/dalvikvm: VFY: unable to resolve direct method 18569: Landroid/widget/LinearLayout$LayoutParams;.<init> (Landroid/widget/LinearLayout$LayoutParams;)V
12-02 02:50:41.189 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: VFY: replacing opcode 0x70 at 0x0000
12-02 02:50:41.254 21762-21762/com.example.qeantx_pc.test2 D/libEGL: loaded /system/lib/egl/libEGL_mali.so
12-02 02:50:41.254 21762-21762/com.example.qeantx_pc.test2 D/libEGL: loaded /system/lib/egl/libGLESv1_CM_mali.so
12-02 02:50:41.254 21762-21762/com.example.qeantx_pc.test2 D/libEGL: loaded /system/lib/egl/libGLESv2_mali.so
12-02 02:50:41.289 21762-21762/com.example.qeantx_pc.test2 D/OpenGLRenderer: Enabling debug mode 0
12-02 02:50:41.314 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: Trying to load lib /data/data/com.example.qeantx_pc.test2/libs/libstlport_shared.so 0x41f8bd20
12-02 02:50:41.314 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: Added shared lib /data/data/com.example.qeantx_pc.test2/libs/libstlport_shared.so 0x41f8bd20
12-02 02:50:41.314 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: No JNI_OnLoad found in /data/data/com.example.qeantx_pc.test2/libs/libstlport_shared.so 0x41f8bd20, skipping init
12-02 02:50:41.314 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: Trying to load lib /data/data/com.example.qeantx_pc.test2/libs/libvplayer.so 0x41f8bd20
12-02 02:50:41.314 21762-21762/com.example.qeantx_pc.test2 D/dalvikvm: Added shared lib /data/data/com.example.qeantx_pc.test2/libs/libvplayer.so 0x41f8bd20
12-02 02:50:41.314 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: Copyright (c) YIXIA (http://yixia.com).
                                                                                     THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
12-02 02:50:41.314 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: LOAD FFMPEG START: /data/data/com.example.qeantx_pc.test2/libs/libffmpeg.so
12-02 02:50:41.319 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: LOAD FFMPEG END: /data/data/com.example.qeantx_pc.test2/libs/libffmpeg.so
12-02 02:50:41.319 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: LOAD VVO START: /data/data/com.example.qeantx_pc.test2/libs/libvvo.9.so
12-02 02:50:41.319 21762-21762/com.example.qeantx_pc.test2 E/Vitamio[4.2.6][Player]: FIND_NAME_SYM vvo, render_yuv
12-02 02:50:41.319 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: LOAD VVO END: /data/data/com.example.qeantx_pc.test2/libs/libvvo.9.so
12-02 02:50:41.319 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: LOAD VAO START: /data/data/com.example.qeantx_pc.test2/libs/libvao.0.so
12-02 02:50:41.324 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: LOAD VAO END: /data/data/com.example.qeantx_pc.test2/libs/libvao.0.so
12-02 02:50:41.324 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: VPLAYER INIT BEGIN
12-02 02:50:41.324 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: Application package name: com.example.qeantx_pc.test2
12-02 02:50:41.329 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: VPLAYER INIT END
12-02 02:50:41.329 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: Copyright (c) YIXIA (http://yixia.com).
                                                                                     THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
12-02 02:50:41.329 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: Application package name: com.example.qeantx_pc.test2
12-02 02:50:41.329 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: Copyright (c) YIXIA (http://yixia.com).
                                                                                     THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
12-02 02:50:41.329 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: Application package name: com.example.qeantx_pc.test2
12-02 02:50:41.329 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: PREPARE SIG: 0
12-02 02:50:41.329 21762-21810/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: THREAD PREPARE START
12-02 02:50:41.329 21762-21810/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: THREAD PREPARE ATTACHED
12-02 02:50:41.329 21762-21810/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: Copyright (c) YIXIA (http://yixia.com).
                                                                                     THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
12-02 02:50:41.329 21762-21810/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: OPEN FILE rtmp://106.248.243.130:8080/live/ht_01&autoplay=true&playerID=player-container
12-02 02:50:41.389 21762-21764/com.example.qeantx_pc.test2 D/dalvikvm: GC_CONCURRENT freed 160K, 9% free 12645K/13767K, paused 12ms+13ms, total 39ms
12-02 02:50:41.824 21762-21810/com.example.qeantx_pc.test2 E/Vitamio[4.2.6][Player]: av_find_stream_info: End of file : -541478725
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 E/Vitamio[4.2.6][Player]: error (1, -541478725)
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FILE CLOSE BEGIN
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: CLOSE AVFORMAT BEGIN
12-02 02:50:41.824 21762-21810/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: THREAD PREPARE DETTACHED, ret = 0
12-02 02:50:41.824 21762-21810/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: THREAD PREPARE END
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: CLOSE AVFORMAT END
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FREE VIDEOPIC BEGIN
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FREE VIDEOPIC 2 END
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FREE SUBPIC BEGIN
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FREE SUBPIC 1 END
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FREE AUDIOFRAME BEGIN
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FREE AUDIOFRAME 8 END
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: DELETE GLOBAL REF BEGIN
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: DELETE GLOBAL REF END
12-02 02:50:41.824 21762-21809/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: FILE CLOSE END
12-02 02:50:41.904 21762-21762/com.example.qeantx_pc.test2 E/Vitamio[Player]: Error (1, -541478725)
12-02 02:51:24.394 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: VPLAYER RELEASE BEGIN
12-02 02:51:24.394 21762-21762/com.example.qeantx_pc.test2 I/Vitamio[4.2.6][Player]: VPLAYER RELEASE END

and my android source code

```
    if (!LibsChecker.checkVitamioLibs(this))
        return;
    setContentView(R.layout.activity_main);
    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    setSupportActionBar(toolbar);

    FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
    fab.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                    .setAction("Action", null).show();
        }
    });

    mVideoView = (VideoView) findViewById(R.id.vitamio_videoView);
    path1 = "rtmp://106.248.243.130:8080/live/ht_01&autoplay=true&playerID=player-container";
    mVideoView.setVideoPath(path1);
    mVideoView.setMediaController(new MediaController(this));
    mVideoView.requestFocus();

    mVideoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
        @Override
        public void onPrepared(MediaPlayer mediaPlayer) {
            mediaPlayer.setPlaybackSpeed(1.0f);
        }
    });
```

and build.gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

```
defaultConfig {
    applicationId "com.example.qeantx_pc.test2"
    minSdkVersion 15
    targetSdkVersion 21
    versionCode 1
    versionName "1.0"
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile project(':vitamio')
}

and manifast.xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.qeantx_pc.test2">

```
<uses-permission android:name="android.permission.INTERNET"/>

<application
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:supportsRtl="true"
    android:theme="@style/AppTheme">
    <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:theme="@style/AppTheme.NoActionBar">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>
</application>
```

</manifest>

and contants_main.xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.example.qeantx_pc.test2.MainActivity"
    tools:showIn="@layout/activity_main">

```
<io.vov.vitamio.widget.VideoView
    android:id="@+id/vitamio_videoView"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />
```

</RelativeLayout>

i see this code in internet...
but i don't know what is the problem
and sorry, it's too long...

**Comment by MythodeaLoL** [comment]
Try

```
path1 = "rtmp://106.248.243.130:8080/live/ht_01&autoplay=true&playerID=player-container";
mVideoView.setVideoPath(Uri.parse(path1));
```

You need to `parse` URI. @qetchx 

<b>When all is resolved, remember to close the issue.</b> :sunglasses:

**Comment by qetchx** [comment]
thanks!! but when i try this string "mVideoView.setVideoPath(Uri.parse(path1));"
i tackled some error "Error:(374, 27) error: incompatible types: Uri cannot be converted to String"

Uri.parse return type is Uri... and maybe this is not convert string type

**Comment by qetchx** [comment]
sorry i realize what you mean!
and thanks, i solve this problem
