### ISSUE TITLE
升级官网的5.0版本后报错

### ISSUE THREAD

**Issue by yilylong** [yixia/VitamioBundle#329]
升级后查看Vitamio这个类里面少了很多方法。貌似并没有做释放so库的动作啊

**Comment by MythodeaLoL** [comment]
Use stable version 4.2.2 @yilylong

**Comment by yilylong** [comment]
@FloridaStream 4.2.2 has security vulnerabilities .Official les us make updates to 5.0

**Comment by yilylong** [comment]
问题解决了。最新版的改了libs文件结构。而库结构本采用的Eclipse的工程结构。我使用的是Android Studio 。 so库 放的位置不对。无法释放。放到src/main/Jinlib/ 下就可以了
