### ISSUE TITLE
Does Vitamio support FCSubscribe?

### ISSUE THREAD

**Issue by NisonLi** [yixia/VitamioBundle#359]
As title , i try to play a rtmp video with vitamio , but it can't work
and i find the reason is FCSubscribe
Is anyone know  that Vitamio support FCSubscibe?

**Comment by MythodeaLoL** [comment]
Tell more about it.

**Comment by NisonLi** [comment]
When streaming RTMP live streams using the Akamai, Edgecast or Limelight CDN, players cannot simply connect to the live stream. Instead, they have to subscribe to it, by sending a so-called FC Subscribe call to the server.

So i think i should to this (send subscribe to server), is any idea for this?

**Comment by MythodeaLoL** [comment]
@NisonLi 
I dont know if this is enable on ffmpeg, but try this command subscribe

> Name of live stream to subscribe to. Defaults to rtmp_**playpath**

I dont know if you need this, or if this exit on ffmpeg used by vitamio, but is good try.

_rtmp://sample.com/path/filename_sample_

```
options.put("rtmp_subscribe", "filename_sample");
mVideoView.setVideoURI(Uri.parse(path), options);
```

or ffmpeg command `--subscribe` to link path. 
crazy sample, sorry
**REF:**http://ffmpeg.org/pipermail/ffmpeg-cvslog/2012-August/053409.html and Google

_I will investigate this as soon as possible, any news I inform you here_
**Please always returns some feedback if you can solve it is very important for everyone, goodbye**

**Comment by NisonLi** [comment]
@FloridaStream 

```
options.put("rtmp_subscribe", "filename_sample");
mVideoView.setVideoURI(Uri.parse(path), options);
```

It is work for me :)

Finally i can see the video by vitamio, and thank you for share this way to solve my problem :D
