### ISSUE TITLE
play finish will death

### ISSUE THREAD

**Issue by fengivy** [yixia/VitamioBundle#368]
04-13 11:13:44.321 26386-26407/com.ivy.test:vitamio D/Vitamio[5.0.0][Player]: Received seek complete
04-13 11:13:44.461 26386-26386/com.ivy.test:vitamio I/Vitamio[5.0.0][Player]: start
04-13 11:13:47.197 26386-26417/com.ivy.test:vitamio A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 26417 (Thread-353)

**Comment by MythodeaLoL** [comment]
You can not test with another stream and see if the same error?

**Comment by fengivy** [comment]
this is video problem! It is ok when i change another video
