### ISSUE TITLE
Android Vitamio couldn't play HD videos.

### ISSUE THREAD

**Issue by pmathew92** [yixia/VitamioBundle#387]
Hey I am trying to build an app that can stream HD videos from a server . I have integrated vitamio in my app but each time I try to play an HD video(now,from my external storage) it says can't play this video.??

I am attaching my code:

import android.net.Uri;
import android.os.Environment;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import io.vov.vitamio.LibsChecker;

public class MainActivity extends AppCompatActivity {
    private io.vov.vitamio.widget.VideoView videoView;

```
private io.vov.vitamio.widget.MediaController mediaController;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    if(!LibsChecker.checkVitamioLibs(this))
        return;
    setContentView(R.layout.activity_main);
    videoView=(io.vov.vitamio.widget.VideoView)findViewById(R.id.vitamioView);

    mediaController=new io.vov.vitamio.widget.MediaController(this);
    mediaController.setAnchorView(videoView);
    videoView.setMediaController(mediaController);
    try{
        Uri videoUri= Uri.parse("http://www.veoh.com/watch/v90285702kEk3RXEm");
        // videoView.setVideoURI(videoUri);
       videoView.setVideoPath(Environment.getExternalStorageDirectory().getPath()+"/video2.mp4");
    }catch(Exception e)
    {
        e.printStackTrace();
        Log.d("Video Error",e.toString());
    }

    videoView.requestFocus();
   videoView.setOnPreparedListener(new io.vov.vitamio.MediaPlayer.OnPreparedListener() {
       @Override
       public void onPrepared(io.vov.vitamio.MediaPlayer mp) {
           videoView.start();
           mp.setPlaybackSpeed(1.0f);
       }
   });



}
```

}

My Manifest File :+1: 

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.wizroots.sample.vitamiovideo" >
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>

```
<application
    android:allowBackup="true"
    android:icon="@mipmap/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/AppTheme" >
    <activity
        android:name=".MainActivity"
        android:label="@string/app_name" >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>

    <!--<activity-->
        <!--android:name="io.vov.vitamio.activity.InitActivity"-->
        <!--android:configChanges="orientation|screenSize|smallestScreenSize|keyboard|keyboardHidden|navigation"-->
        <!--android:launchMode="singleTop"-->
        <!--android:theme="@android:style/Theme.NoTitleBar"-->
        <!--android:windowSoftInputMode="stateAlwaysHidden" />-->
</application>
```

</manifest>

**Comment by MythodeaLoL** [comment]
Post log errors @pmathew92

**Comment by pmathew92** [comment]
@FloridaStream Hey this is what the log showed while trying to stream an HQ video online...

06-08 12:29:07.105  31181-31181/? I/art﹕ Late-enabling -Xcheck:jni
06-08 12:29:07.265  31181-31181/? W/art﹕ Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
06-08 12:29:07.334  31181-31181/? I/ViewRootImpl﹕ CPU Rendering VSync enable = true
06-08 12:29:07.335  31181-31206/? D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
06-08 12:29:07.342  31181-31181/? D/Atlas﹕ Validating map...
06-08 12:29:07.386  31181-31206/? I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.4_RB1__release_AU (Ibddc658e36)
    OpenGL ES Shader Compiler Version: E031.25.03.04
    Build Date: 10/13/15 Tue
    Local Branch: mybranch15212261
    Remote Branch: quic/LA.BR.1.2.4_rb1.24
    Local Patches: NONE
    Reconstruct Branch: NOTHING
06-08 12:29:07.388  31181-31206/? I/OpenGLRenderer﹕ Initialized EGL, version 1.4
06-08 12:29:07.414  31181-31206/? D/OpenGLRenderer﹕ Enabling debug mode 0
06-08 12:29:07.462  31181-31181/? I/Vitamio[4.2.6][Player]﹕ Copyright (c) YIXIA (http://yixia.com).
    THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
06-08 12:29:07.462  31181-31181/? I/Vitamio[4.2.6][Player]﹕ LOAD FFMPEG START: /data/data/com.wizroots.sample.vitamiovideo/libs/libffmpeg.so
06-08 12:29:07.470  31181-31181/? W/linker﹕ libffmpeg.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
06-08 12:29:07.479  31181-31181/? I/Vitamio[4.2.6][Player]﹕ LOAD FFMPEG END: /data/data/com.wizroots.sample.vitamiovideo/libs/libffmpeg.so
06-08 12:29:07.479  31181-31181/? I/Vitamio[4.2.6][Player]﹕ LOAD VVO START: /data/data/com.wizroots.sample.vitamiovideo/libs/libvvo.9.so
06-08 12:29:07.481  31181-31181/? E/Vitamio[4.2.6][Player]﹕ FIND_NAME_SYM vvo, render_yuv
06-08 12:29:07.482  31181-31181/? I/Vitamio[4.2.6][Player]﹕ LOAD VVO END: /data/data/com.wizroots.sample.vitamiovideo/libs/libvvo.9.so
06-08 12:29:07.482  31181-31181/? I/Vitamio[4.2.6][Player]﹕ LOAD VAO START: /data/data/com.wizroots.sample.vitamiovideo/libs/libvao.0.so
06-08 12:29:07.483  31181-31181/? I/Vitamio[4.2.6][Player]﹕ LOAD VAO END: /data/data/com.wizroots.sample.vitamiovideo/libs/libvao.0.so
06-08 12:29:07.483  31181-31181/? I/Vitamio[4.2.6][Player]﹕ VPLAYER INIT BEGIN
06-08 12:29:07.483  31181-31181/? I/Vitamio[4.2.6][Player]﹕ Application package name: com.wizroots.sample.vitamiovideo
06-08 12:29:07.492  31181-31181/? I/Vitamio[4.2.6][Player]﹕ VPLAYER INIT END
06-08 12:29:07.493  31181-31181/? I/Vitamio[4.2.6][Player]﹕ Copyright (c) YIXIA (http://yixia.com).
    THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
06-08 12:29:07.493  31181-31181/? I/Vitamio[4.2.6][Player]﹕ Application package name: com.wizroots.sample.vitamiovideo
06-08 12:29:07.493  31181-31181/? I/Vitamio[4.2.6][Player]﹕ Copyright (c) YIXIA (http://yixia.com).
    THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
06-08 12:29:07.493  31181-31181/? I/Vitamio[4.2.6][Player]﹕ Application package name: com.wizroots.sample.vitamiovideo
06-08 12:29:07.493  31181-31181/? I/Vitamio[4.2.6][Player]﹕ PREPARE SIG: 0
06-08 12:29:07.494  31181-31211/? I/Vitamio[4.2.6][Player]﹕ THREAD PREPARE START
06-08 12:29:07.494  31181-31211/? I/Vitamio[4.2.6][Player]﹕ THREAD PREPARE ATTACHED
06-08 12:29:07.495  31181-31211/? I/Vitamio[4.2.6][Player]﹕ Copyright (c) YIXIA (http://yixia.com).
    THIS SOFTWARE (Vitamio) IS WORK OF YIXIA (http://yixia.com)
06-08 12:29:07.495  31181-31211/? I/Vitamio[4.2.6][Player]﹕ OPEN FILE http://qan.vc/file/download/33594
06-08 12:29:07.574  31181-31181/? I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@31576af time:82763268
06-08 12:29:09.262  31181-31211/? E/Vitamio[4.2.6][Player]﹕ avformat_open_input: I/O error : -5
06-08 12:29:09.262  31181-31210/? E/Vitamio[4.2.6][Player]﹕ error (1, -5)
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FILE CLOSE BEGIN
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FREE VIDEOPIC BEGIN
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FREE VIDEOPIC 2 END
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FREE SUBPIC BEGIN
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FREE SUBPIC 1 END
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FREE AUDIOFRAME BEGIN
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FREE AUDIOFRAME 8 END
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ DELETE GLOBAL REF BEGIN
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ DELETE GLOBAL REF END
06-08 12:29:09.262  31181-31210/? I/Vitamio[4.2.6][Player]﹕ FILE CLOSE END
06-08 12:29:09.262  31181-31211/? I/Vitamio[4.2.6][Player]﹕ THREAD PREPARE DETTACHED, ret = 0
06-08 12:29:09.262  31181-31211/? I/Vitamio[4.2.6][Player]﹕ THREAD PREPARE END
06-08 12:29:09.343  31181-31181/? E/Vitamio[Player]﹕ Error (1, -5)
06-08 12:29:09.372  31181-31181/? I/ViewRootImpl﹕ CPU Rendering VSync enable = true
06-08 12:29:11.999  31181-31181/? I/Vitamio[4.2.6][Player]﹕ VPLAYER RELEASE BEGIN
06-08 12:29:11.999  31181-31181/? I/Vitamio[4.2.6][Player]﹕ VPLAYER RELEASE END

**Comment by MythodeaLoL** [comment]
try this @pmathew92 

``` javascript
import android.net.Uri;
import android.os.Environment;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import io.vov.vitamio.LibsChecker;

public class MainActivity extends AppCompatActivity {
private io.vov.vitamio.widget.VideoView videoView;
private String path;
private io.vov.vitamio.widget.MediaController mediaController;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    if(!LibsChecker.checkVitamioLibs(this))
        return;
    setContentView(R.layout.activity_main);
    videoView=(io.vov.vitamio.widget.VideoView)findViewById(R.id.vitamioView);

    mediaController=new io.vov.vitamio.widget.MediaController(this);
    mediaController.setAnchorView(videoView);
    videoView.setMediaController(mediaController);

        path = "http://qan.vc/file/download/33594";
        videoView.setVideoURI(Uri.parse(path));

    videoView.requestFocus();
    videoView.setOnPreparedListener(new io.vov.vitamio.MediaPlayer.OnPreparedListener() {
       @Override
       public void onPrepared(io.vov.vitamio.MediaPlayer mp) {
           videoView.start();
           mp.setPlaybackSpeed(1.0f);
       }
   });
 }
}
```

Your code can be improved, take a look at the examples.

**Comment by pmathew92** [comment]
Hey it played the link you mentioned but didn't play this link:

http://qan.vc/file/download/33564

**Comment by MythodeaLoL** [comment]
I cant help with functios out of vitamio, try direct link to mp4 without site redirect.
