### ISSUE TITLE
两部手机，小米可以正常播放，华为荣耀6报错，vplayer也可以正常播放（5.0.1）

### ISSUE THREAD

**Issue by stevenMieMie** [yixia/VitamioBundle#393]
华为是的错误如下：
07-05 14:31:14.725 2876-2903/? E/SQLiteLog: (5) statement aborts at 1: [PRAGMA journal_mode=PERSIST] 
07-05 14:31:15.555 2488-2488/? E/Vitamio[5.0.2][Player]: FIND_NAME_SYM ffmpeg, ff_ass_split
07-05 14:31:15.555 2488-2488/? E/Vitamio[5.0.2][Player]: FIND_NAME_SYM ffmpeg, ff_ass_split_dialog
07-05 14:31:15.555 2488-2488/? E/Vitamio[5.0.2][Player]: FIND_NAME_SYM ffmpeg, ff_ass_split_free
07-05 14:31:15.555 2488-2488/? E/Vitamio[5.0.2][Player]: FIND_NAME_SYM ffmpeg, av_close_input_file
07-05 14:31:15.555 2488-2488/? E/Vitamio[5.0.2][Player]: FIND_NAME_SYM vvo, render_yuv
07-05 14:31:15.695 2488-3594/? E/Vitamio[5.0.2][Player]: avformat_open_input: Invalid data found when processing input : -1094995529
07-05 14:31:15.695 2488-3593/? E/Vitamio[5.0.2][Player]: error (1, -1094995529)

**Comment by MythodeaLoL** [comment]
**Relevant** https://github.com/yixia/VitamioBundle/issues/399#issuecomment-233160210
_Vitamio 5.0.2 can't play any live stream_
