### ISSUE TITLE
No sound in video

### ISSUE THREAD

**Issue by marva2013** [yixia/VitamioBundle#431]
When i play a streaming video i can't find any sound and i find this error : 
FIND_NAME_SYM ffmpeg, ff_ass_split
FIND_NAME_SYM ffmpeg, ff_ass_split_dialog
FIND_NAME_SYM ffmpeg, ff_ass_split_free
FIND_NAME_SYM ffmpeg, av_close_input_file
FIND_NAME_SYM vvo, render_yuv
Please help me to resolve this.
Thanks

**Comment by MythodeaLoL** [comment]
FIND_NAME_SYM is a problem with your version/or ffmpeg compilation problem. Please close issue and **[search (https://github.com/yixia/VitamioBundle/issues?utf8=%E2%9C%93&q=FIND_NAME_SYM)](https://github.com/yixia/VitamioBundle/issues?utf8=%E2%9C%93&q=FIND_NAME_SYM)**.

**Comment by marva2013** [comment]
Thanks FloridaStream
