### ISSUE TITLE
rtsp streaming not working

### ISSUE THREAD

**Issue by joncevski** [yixia/VitamioBundle#53]
Tried to play rtsp stream and get this error:

Fatal signal 11 (SIGSEGV) at 0x00000058 (code=1), thread 10851 (ov.vitamio.demo)

Here is the stream rtsp://62.162.58.55/TVTera
It's playing in VLC.
Thanks

**Comment by yusufonderd** [comment]
I have same issue . I am getting 454 sesion not found . My code as below : 

`public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";
    private String path;
    //private HashMap<String, String> options;
    private VideoView mVideoView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        if (!LibsChecker.checkVitamioLibs(this))
            return;
        setContentView(R.layout.activity_main);
        mVideoView = (VideoView) findViewById(R.id.vitamio_videoView);
        path = "rtsp://localip:554/sub1";

```
    mVideoView.setVideoPath(path);
    mVideoView.setMediaController(new MediaController(this));

    mVideoView.requestFocus();

    mVideoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
        @Override
        public void onPrepared(MediaPlayer mediaPlayer) {
            mediaPlayer.setPlaybackSpeed(1.0f);
        }
    });


}
```

}`
How can I solve ?
