### ISSUE TITLE
Switching between quality in a HLS stream.

### ISSUE THREAD

**Issue by cuki** [yixia/VitamioBundle#6]
When playing a HLS m3u8 index file that contains multiple qualities, for example:
http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

It always plays first stream resource that is available in the index file, which is http://devimages.apple.com/iphone/samples/bipbop/gear1/prog_index.m3u8 the _lowest_ quality in this m3u8 index file.

I tried switching between quality by setting the video quality in the VideoView by using setVideoQuality:
- mVideoView.setVideoQuality( **MediaPlayer.VIDEOQUALITY_LOW** );
- mVideoView.setVideoQuality( **MediaPlayer.VIDEOQUALITY_MEDIUM** );
- mVideoView.setVideoQuality( **MediaPlayer.VIDEOQUALITY_HIGH** );

But it always keeps playing the same stream resource, the first one in the m3u8 index file.

Or is there a different function in Vitamio that automatically switches between stream qualities based on bandwidth connection?

**Comment by deepakdubeycnvg** [comment]
.m3u8 work perfectly in jcvideoplayer on marshmallow but in lower version of device its  not working

please help
