### ISSUE TITLE
Error on Android 4.3: LOCK BUFFER FAILED

### ISSUE THREAD

**Issue by minhtoantm** [yixia/VitamioBundle#60]
Hi Cross.
I report this error with you, But it is still appear in case:
I have 4 video with fomart 240p, 360p, 480p, 720p. When I'm play 240p, and switch to 360p, 480p, 720p, It has error.
Can you check and fix it?

**Comment by MythodeaLoL** [comment]
Thanks minhtoantm  for posting your code, @minhtoantm 
He corrected my bug, always loading and did not start. (4.2.2)

**Comment by yfzu** [comment]
ccc
