### ISSUE TITLE
FIND_NAME_SYM vvo, render_yuv

### ISSUE THREAD

**Issue by safarious** [yixia/VitamioBundle#82]
When I start the app and do Vitamio.initalize(this, R.raw.libarm). I get following output in Logcat:

LOAD FFMPEG START: /data/data/de.test/libs/libffmpeg.so
LOAD FFMPEG END: /data/data/de.test/libs/libffmpeg.so
LOAD VVO START: /data/data/de.test/libs/libvvo.9.so
FIND_NAME_SYM vvo, render_yuv  <-- Is marked Red, something seems to be wrong
LOAD VVO END: /data/data/de.test/libs/libvvo.9.so
LOAD VAO START: /data/data/de.test/libs/libvao.0.so
LOAD VAO END: /data/data/de.test/libs/libvao.0.so
VPLAYER INIT BEGIN

What do I need to change, to get that loading like it should.

Regards

safari

**Comment by ghost** [comment]
@safarious Hi everyone,
I am facing the same issue...Can you please provide the solution here (As It has been closed by you.)?
Thanks.

**Comment by MythodeaLoL** [comment]
Ignore this error @ram10609601

**Comment by ghost** [comment]
Thanks Florida for quick response.

**Comment by safarious** [comment]
@ram10609601 @FloridaStream Exactly!
