### ISSUE TITLE
can't launch rtmp streams with -T rtmpdump parameter

### ISSUE THREAD

**Issue by BufferUnderflower** [yixia/VitamioBundle#87]
I can play this stream with ffmpeg , rtmpGUI but not using Vitamio

rtmpdump -r rtmp://nyk.premiumcdnlive.com/edge -W http://player.ilive.to/secure_player_ilive_z.swf -o- -T I8772LDKksadhGHGagf# -b 96000000  -p http://www.ilive.to/ -y fg2fwiffpklotoc

**Comment by MythodeaLoL** [comment]
@Lolshtole you successful compiled vitamio + rtmpdump? Please help me. https://github.com/yixia/VitamioBundle/issues/283
